exclude: "docs|node_modules|.git"
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
